### YamlMime:ManagedReference
items:
- uid: Steam.KeyValues.KeyValueConvert
  commentId: T:Steam.KeyValues.KeyValueConvert
  id: KeyValueConvert
  parent: Steam.KeyValues
  children:
  - Steam.KeyValues.KeyValueConvert.DeserializeObject``1(System.String)
  - Steam.KeyValues.KeyValueConvert.PopulateObject(System.Object,System.String)
  langs:
  - csharp
  - vb
  name: KeyValueConvert
  nameWithType: KeyValueConvert
  fullName: Steam.KeyValues.KeyValueConvert
  type: Class
  source:
    id: KeyValueConvert
    path: G:\Steam\src\Common\Steam.KeyValues\KeyValueConvert.cs
    startLine: 6
  assemblies:
  - Steam.KeyValues
  namespace: Steam.KeyValues
  syntax:
    content: public static class KeyValueConvert
    content.vb: Public Module KeyValueConvert
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: Steam.KeyValues.KeyValueConvert.DeserializeObject``1(System.String)
  commentId: M:Steam.KeyValues.KeyValueConvert.DeserializeObject``1(System.String)
  id: DeserializeObject``1(System.String)
  parent: Steam.KeyValues.KeyValueConvert
  langs:
  - csharp
  - vb
  name: DeserializeObject<T>(String)
  nameWithType: KeyValueConvert.DeserializeObject<T>(String)
  fullName: Steam.KeyValues.KeyValueConvert.DeserializeObject<T>(System.String)
  type: Method
  source:
    id: DeserializeObject
    path: G:\Steam\src\Common\Steam.KeyValues\KeyValueConvert.cs
    startLine: 34
  assemblies:
  - Steam.KeyValues
  namespace: Steam.KeyValues
  syntax:
    content: public static T DeserializeObject<T>(string value)
    parameters:
    - id: value
      type: System.String
    typeParameters:
    - id: T
    return:
      type: '{T}'
    content.vb: Public Shared Function DeserializeObject(Of T)(value As String) As T
  overload: Steam.KeyValues.KeyValueConvert.DeserializeObject*
  nameWithType.vb: KeyValueConvert.DeserializeObject(Of T)(String)
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
  fullName.vb: Steam.KeyValues.KeyValueConvert.DeserializeObject(Of T)(System.String)
  name.vb: DeserializeObject(Of T)(String)
- uid: Steam.KeyValues.KeyValueConvert.PopulateObject(System.Object,System.String)
  commentId: M:Steam.KeyValues.KeyValueConvert.PopulateObject(System.Object,System.String)
  id: PopulateObject(System.Object,System.String)
  parent: Steam.KeyValues.KeyValueConvert
  langs:
  - csharp
  - vb
  name: PopulateObject(Object, String)
  nameWithType: KeyValueConvert.PopulateObject(Object, String)
  fullName: Steam.KeyValues.KeyValueConvert.PopulateObject(System.Object, System.String)
  type: Method
  source:
    id: PopulateObject
    path: G:\Steam\src\Common\Steam.KeyValues\KeyValueConvert.cs
    startLine: 39
  assemblies:
  - Steam.KeyValues
  namespace: Steam.KeyValues
  syntax:
    content: public static void PopulateObject(object value, string keyValues)
    parameters:
    - id: value
      type: System.Object
    - id: keyValues
      type: System.String
    content.vb: Public Shared Sub PopulateObject(value As Object, keyValues As String)
  overload: Steam.KeyValues.KeyValueConvert.PopulateObject*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: Steam.KeyValues
  commentId: N:Steam.KeyValues
  isExternal: false
  name: Steam.KeyValues
  nameWithType: Steam.KeyValues
  fullName: Steam.KeyValues
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Steam.KeyValues.KeyValueConvert.DeserializeObject*
  commentId: Overload:Steam.KeyValues.KeyValueConvert.DeserializeObject
  isExternal: false
  name: DeserializeObject
  nameWithType: KeyValueConvert.DeserializeObject
  fullName: Steam.KeyValues.KeyValueConvert.DeserializeObject
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: T
  isExternal: false
  name: T
  nameWithType: T
  fullName: T
- uid: Steam.KeyValues.KeyValueConvert.PopulateObject*
  commentId: Overload:Steam.KeyValues.KeyValueConvert.PopulateObject
  isExternal: false
  name: PopulateObject
  nameWithType: KeyValueConvert.PopulateObject
  fullName: Steam.KeyValues.KeyValueConvert.PopulateObject
