### YamlMime:ManagedReference
items:
- uid: Steam.KeyValues.KeyValuePropertyAttribute
  commentId: T:Steam.KeyValues.KeyValuePropertyAttribute
  id: KeyValuePropertyAttribute
  parent: Steam.KeyValues
  children:
  - Steam.KeyValues.KeyValuePropertyAttribute.#ctor
  - Steam.KeyValues.KeyValuePropertyAttribute.#ctor(System.String)
  - Steam.KeyValues.KeyValuePropertyAttribute.PropertyName
  - Steam.KeyValues.KeyValuePropertyAttribute.Required
  langs:
  - csharp
  - vb
  name: KeyValuePropertyAttribute
  nameWithType: KeyValuePropertyAttribute
  fullName: Steam.KeyValues.KeyValuePropertyAttribute
  type: Class
  source:
    id: KeyValuePropertyAttribute
    path: G:\Steam\src\Common\Steam.KeyValues\KeyValuePropertyAttribute.cs
    startLine: 7
  assemblies:
  - Steam.KeyValues
  namespace: Steam.KeyValues
  summary: "\nInstructs the <see cref=\"!:KeyValueSerializer\"></see> to always serialize this property with the specified name\n"
  example: []
  syntax:
    content: >-
      [AttributeUsage(AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.Property, AllowMultiple = false)]

      public class KeyValuePropertyAttribute : Attribute
    content.vb: >-
      <AttributeUsage(AttributeTargets.Field Or AttributeTargets.Parameter Or AttributeTargets.Property, AllowMultiple:=False)>

      Public Class KeyValuePropertyAttribute

          Inherits Attribute
  inheritance:
  - System.Object
  - System.Attribute
  inheritedMembers:
  - System.Attribute.Equals(System.Object)
  - System.Attribute.GetHashCode
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  attributes:
  - type: System.AttributeUsageAttribute
    ctor: System.AttributeUsageAttribute.#ctor(System.AttributeTargets)
    arguments:
    - type: System.AttributeTargets
      value: 2432
    namedArguments:
    - name: AllowMultiple
      type: System.Boolean
      value: false
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Steam.KeyValues.KeyValuePropertyAttribute.Required
  commentId: P:Steam.KeyValues.KeyValuePropertyAttribute.Required
  id: Required
  parent: Steam.KeyValues.KeyValuePropertyAttribute
  langs:
  - csharp
  - vb
  name: Required
  nameWithType: KeyValuePropertyAttribute.Required
  fullName: Steam.KeyValues.KeyValuePropertyAttribute.Required
  type: Property
  source:
    id: Required
    path: G:\Steam\src\Common\Steam.KeyValues\KeyValuePropertyAttribute.cs
    startLine: 13
  assemblies:
  - Steam.KeyValues
  namespace: Steam.KeyValues
  summary: "\nGets or sets whether this field is required during serialization\n"
  example: []
  syntax:
    content: public bool Required { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property Required As Boolean
  overload: Steam.KeyValues.KeyValuePropertyAttribute.Required*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Steam.KeyValues.KeyValuePropertyAttribute.PropertyName
  commentId: P:Steam.KeyValues.KeyValuePropertyAttribute.PropertyName
  id: PropertyName
  parent: Steam.KeyValues.KeyValuePropertyAttribute
  langs:
  - csharp
  - vb
  name: PropertyName
  nameWithType: KeyValuePropertyAttribute.PropertyName
  fullName: Steam.KeyValues.KeyValuePropertyAttribute.PropertyName
  type: Property
  source:
    id: PropertyName
    path: G:\Steam\src\Common\Steam.KeyValues\KeyValuePropertyAttribute.cs
    startLine: 18
  assemblies:
  - Steam.KeyValues
  namespace: Steam.KeyValues
  summary: "\nGets or sets the property name of this member\n"
  example: []
  syntax:
    content: public string PropertyName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property PropertyName As String
  overload: Steam.KeyValues.KeyValuePropertyAttribute.PropertyName*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Steam.KeyValues.KeyValuePropertyAttribute.#ctor
  commentId: M:Steam.KeyValues.KeyValuePropertyAttribute.#ctor
  id: '#ctor'
  parent: Steam.KeyValues.KeyValuePropertyAttribute
  langs:
  - csharp
  - vb
  name: KeyValuePropertyAttribute()
  nameWithType: KeyValuePropertyAttribute.KeyValuePropertyAttribute()
  fullName: Steam.KeyValues.KeyValuePropertyAttribute.KeyValuePropertyAttribute()
  type: Constructor
  source:
    id: .ctor
    path: G:\Steam\src\Common\Steam.KeyValues\KeyValuePropertyAttribute.cs
    startLine: 23
  assemblies:
  - Steam.KeyValues
  namespace: Steam.KeyValues
  summary: "\nInitializes the attribute with the default values\n"
  example: []
  syntax:
    content: public KeyValuePropertyAttribute()
    content.vb: Public Sub New
  overload: Steam.KeyValues.KeyValuePropertyAttribute.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Steam.KeyValues.KeyValuePropertyAttribute.#ctor(System.String)
  commentId: M:Steam.KeyValues.KeyValuePropertyAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: Steam.KeyValues.KeyValuePropertyAttribute
  langs:
  - csharp
  - vb
  name: KeyValuePropertyAttribute(String)
  nameWithType: KeyValuePropertyAttribute.KeyValuePropertyAttribute(String)
  fullName: Steam.KeyValues.KeyValuePropertyAttribute.KeyValuePropertyAttribute(System.String)
  type: Constructor
  source:
    id: .ctor
    path: G:\Steam\src\Common\Steam.KeyValues\KeyValuePropertyAttribute.cs
    startLine: 29
  assemblies:
  - Steam.KeyValues
  namespace: Steam.KeyValues
  summary: "\nInitializes the attribute with the default values and the specified property name\n"
  example: []
  syntax:
    content: public KeyValuePropertyAttribute(string propertyName)
    parameters:
    - id: propertyName
      type: System.String
      description: ''
    content.vb: Public Sub New(propertyName As String)
  overload: Steam.KeyValues.KeyValuePropertyAttribute.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Steam.KeyValues
  commentId: N:Steam.KeyValues
  isExternal: false
  name: Steam.KeyValues
  nameWithType: Steam.KeyValues
  fullName: Steam.KeyValues
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Attribute
  commentId: T:System.Attribute
  parent: System
  isExternal: true
  name: Attribute
  nameWithType: Attribute
  fullName: System.Attribute
- uid: System.Attribute.Equals(System.Object)
  commentId: M:System.Attribute.Equals(System.Object)
  parent: System.Attribute
  isExternal: true
  name: Equals(Object)
  nameWithType: Attribute.Equals(Object)
  fullName: System.Attribute.Equals(System.Object)
  spec.csharp:
  - uid: System.Attribute.Equals(System.Object)
    name: Equals
    nameWithType: Attribute.Equals
    fullName: System.Attribute.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Attribute.Equals(System.Object)
    name: Equals
    nameWithType: Attribute.Equals
    fullName: System.Attribute.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Attribute.GetHashCode
  commentId: M:System.Attribute.GetHashCode
  parent: System.Attribute
  isExternal: true
  name: GetHashCode()
  nameWithType: Attribute.GetHashCode()
  fullName: System.Attribute.GetHashCode()
  spec.csharp:
  - uid: System.Attribute.GetHashCode
    name: GetHashCode
    nameWithType: Attribute.GetHashCode
    fullName: System.Attribute.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Attribute.GetHashCode
    name: GetHashCode
    nameWithType: Attribute.GetHashCode
    fullName: System.Attribute.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Steam.KeyValues.KeyValuePropertyAttribute.Required*
  commentId: Overload:Steam.KeyValues.KeyValuePropertyAttribute.Required
  isExternal: false
  name: Required
  nameWithType: KeyValuePropertyAttribute.Required
  fullName: Steam.KeyValues.KeyValuePropertyAttribute.Required
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Steam.KeyValues.KeyValuePropertyAttribute.PropertyName*
  commentId: Overload:Steam.KeyValues.KeyValuePropertyAttribute.PropertyName
  isExternal: false
  name: PropertyName
  nameWithType: KeyValuePropertyAttribute.PropertyName
  fullName: Steam.KeyValues.KeyValuePropertyAttribute.PropertyName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Steam.KeyValues.KeyValuePropertyAttribute.#ctor*
  commentId: Overload:Steam.KeyValues.KeyValuePropertyAttribute.#ctor
  isExternal: false
  name: KeyValuePropertyAttribute
  nameWithType: KeyValuePropertyAttribute.KeyValuePropertyAttribute
  fullName: Steam.KeyValues.KeyValuePropertyAttribute.KeyValuePropertyAttribute
